/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.ringcentral.engage-voice;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
